"""Keyword-based store-category guessing (v0.2; widened aisles + word-boundary matching v0.7).

Used wherever an item arrives without a category: URL imports (JSON-LD has no aisle data,
unlike Spoonacular), manual list adds with no history to recall, and a pantry-scan fallback.

Matching rules:
- **Word-boundary, not substring.** "milk collector" no longer reads as *milk* → Dairy just
  because the word "milk" appears inside a larger phrase's neighbor; "eggplant" isn't *egg*,
  "juice" isn't *ice*, "chipotle" isn't *chip*. A keyword matches only as a whole word/phrase.
- **Longest keyword wins**, so a specific phrase beats a generic word it contains
  ("milk collector" → baby beats "milk" → dairy; "black pepper" → pantry beats "pepper" →
  produce; "chocolate chip" → pantry beats "chocolate" → snacks).
- **A miss returns None** and the item lands in "Other" — guessing wrong is worse than not
  guessing.

Keywords are stored in their normalized-singular form (see `normalize_name`), lowercase.
"""

import re

from app.lists.merge import normalize_name

# keyword (normalized, singular) -> category.
_KEYWORDS: dict[str, str] = {
    # ── produce ──────────────────────────────────────────────────────────────
    "onion": "produce",
    "garlic": "produce",
    "tomato": "produce",
    "potato": "produce",
    "sweet potato": "produce",
    "carrot": "produce",
    "celery": "produce",
    "pepper": "produce",
    "bell pepper": "produce",
    "jalapeno": "produce",
    "lettuce": "produce",
    "romaine": "produce",
    "arugula": "produce",
    "spinach": "produce",
    "kale": "produce",
    "broccoli": "produce",
    "cauliflower": "produce",
    "cucumber": "produce",
    "zucchini": "produce",
    "squash": "produce",
    "mushroom": "produce",
    "avocado": "produce",
    "lemon": "produce",
    "lime": "produce",
    "orange": "produce",
    "apple": "produce",
    "banana": "produce",
    "berry": "produce",
    "strawberry": "produce",
    "blueberry": "produce",
    "raspberry": "produce",
    "grape": "produce",
    "melon": "produce",
    "watermelon": "produce",
    "cantaloupe": "produce",
    "pear": "produce",
    "peach": "produce",
    "plum": "produce",
    "mango": "produce",
    "pineapple": "produce",
    "kiwi": "produce",
    "cherry": "produce",
    "radish": "produce",
    "beet": "produce",
    "turnip": "produce",
    "leek": "produce",
    "eggplant": "produce",
    "cilantro": "produce",
    "parsley": "produce",
    "basil": "produce",
    "thyme": "produce",
    "rosemary": "produce",
    "ginger": "produce",
    "scallion": "produce",
    "green onion": "produce",
    "shallot": "produce",
    "cabbage": "produce",
    "corn": "produce",
    "green bean": "produce",
    "asparagus": "produce",
    "brussels sprout": "produce",
    "salad": "produce",
    "herb": "produce",
    # ── meat & seafood ───────────────────────────────────────────────────────
    "chicken": "meat",
    "beef": "meat",
    "pork": "meat",
    "turkey": "meat",
    "lamb": "meat",
    "bacon": "meat",
    "sausage": "meat",
    "ham": "meat",
    "steak": "meat",
    "ground beef": "meat",
    "ground turkey": "meat",
    "ground": "meat",
    "salmon": "meat",
    "shrimp": "meat",
    "tuna": "meat",
    "fish": "meat",
    "cod": "meat",
    "tilapia": "meat",
    "crab": "meat",
    "lobster": "meat",
    "scallop": "meat",
    "mussel": "meat",
    "clam": "meat",
    "catfish": "meat",
    "halibut": "meat",
    "brisket": "meat",
    "rib": "meat",
    "pork chop": "meat",
    "meatball": "meat",
    "veal": "meat",
    "duck": "meat",
    "filet": "meat",
    "tenderloin": "meat",
    "drumstick": "meat",
    "chicken thigh": "meat",
    "chicken breast": "meat",
    # ── deli ─────────────────────────────────────────────────────────────────
    "deli": "deli",
    "lunch meat": "deli",
    "deli meat": "deli",
    "prosciutto": "deli",
    "salami": "deli",
    "pepperoni": "deli",
    "bologna": "deli",
    "pastrami": "deli",
    "capicola": "deli",
    "mortadella": "deli",
    "corned beef": "deli",
    "rotisserie": "deli",
    # ── dairy & eggs ─────────────────────────────────────────────────────────
    "milk": "dairy",
    "almond milk": "dairy",
    "oat milk": "dairy",
    "soy milk": "dairy",
    "cheese": "dairy",
    "cheddar": "dairy",
    "mozzarella": "dairy",
    "parmesan": "dairy",
    "gouda": "dairy",
    "brie": "dairy",
    "swiss": "dairy",
    "provolone": "dairy",
    "feta": "dairy",
    "ricotta": "dairy",
    "cottage cheese": "dairy",
    "cream cheese": "dairy",
    "string cheese": "dairy",
    "butter": "dairy",
    "margarine": "dairy",
    "yogurt": "dairy",
    "buttermilk": "dairy",  # explicit: word-boundary matching won't split the compound word
    "cream": "dairy",
    "sour cream": "dairy",
    "whipped cream": "dairy",
    "half and half": "dairy",
    "creamer": "dairy",
    "kefir": "dairy",
    "egg": "dairy",
    # ── bakery ───────────────────────────────────────────────────────────────
    "bread": "bakery",
    "bun": "bakery",
    "roll": "bakery",
    "dinner roll": "bakery",
    "tortilla": "bakery",
    "bagel": "bakery",
    "pita": "bakery",
    "naan": "bakery",
    "croissant": "bakery",
    "baguette": "bakery",
    "brioche": "bakery",
    "focaccia": "bakery",
    "muffin": "bakery",
    "donut": "bakery",
    "doughnut": "bakery",
    "cake": "bakery",
    "cupcake": "bakery",
    "danish": "bakery",
    "scone": "bakery",
    # ── frozen ───────────────────────────────────────────────────────────────
    "frozen": "frozen",
    "ice cream": "frozen",
    "popsicle": "frozen",
    "ice pop": "frozen",
    "waffle": "frozen",
    "ice": "frozen",
    # ── pantry (dry goods, canned, baking, condiments, spices) ────────────────
    "flour": "pantry",
    "sugar": "pantry",
    "brown sugar": "pantry",
    "powdered sugar": "pantry",
    "salt": "pantry",
    "oil": "pantry",
    "olive oil": "pantry",
    "vinegar": "pantry",
    "rice": "pantry",
    "pasta": "pantry",
    "noodle": "pantry",
    "ramen": "pantry",
    "bean": "pantry",
    "lentil": "pantry",
    "broth": "pantry",
    "stock": "pantry",
    "soup": "pantry",
    "sauce": "pantry",
    "tomato sauce": "pantry",
    "pasta sauce": "pantry",
    "paste": "pantry",
    "tomato paste": "pantry",
    "canned": "pantry",
    "coconut milk": "pantry",
    "condensed milk": "pantry",
    "evaporated milk": "pantry",
    "cereal": "pantry",
    "oatmeal": "pantry",
    "oat": "pantry",
    "honey": "pantry",
    "syrup": "pantry",
    "maple syrup": "pantry",
    "spice": "pantry",
    "black pepper": "pantry",
    "cumin": "pantry",
    "paprika": "pantry",
    "oregano": "pantry",
    "cinnamon": "pantry",
    "vanilla": "pantry",
    "garlic powder": "pantry",
    "onion powder": "pantry",
    "chili powder": "pantry",
    "taco seasoning": "pantry",
    "baking powder": "pantry",
    "baking soda": "pantry",
    "cornstarch": "pantry",
    "corn starch": "pantry",
    "bread crumb": "pantry",
    "yeast": "pantry",
    "cocoa": "pantry",
    "chocolate chip": "pantry",
    "peanut butter": "pantry",
    "almond butter": "pantry",
    "jam": "pantry",
    "jelly": "pantry",
    "mayo": "pantry",
    "mayonnaise": "pantry",
    "mustard": "pantry",
    "ketchup": "pantry",
    "soy sauce": "pantry",
    "hot sauce": "pantry",
    "bbq sauce": "pantry",
    "salsa": "pantry",
    "dressing": "pantry",
    "ranch": "pantry",
    "olive": "pantry",
    "pickle": "pantry",
    "relish": "pantry",
    "gravy": "pantry",
    "stuffing": "pantry",
    "couscous": "pantry",
    "quinoa": "pantry",
    "barley": "pantry",
    "grits": "pantry",
    "molasses": "pantry",
    "pancake mix": "pantry",
    # ── snacks ───────────────────────────────────────────────────────────────
    "chip": "snacks",
    "potato chip": "snacks",
    "tortilla chip": "snacks",
    "cracker": "snacks",
    "cookie": "snacks",
    "candy": "snacks",
    "chocolate": "snacks",
    "chocolate bar": "snacks",
    "candy bar": "snacks",
    "pretzel": "snacks",
    "popcorn": "snacks",
    "granola": "snacks",
    "granola bar": "snacks",
    "protein bar": "snacks",
    "trail mix": "snacks",
    "nut": "snacks",
    "mixed nut": "snacks",
    "almond": "snacks",
    "cashew": "snacks",
    "pecan": "snacks",
    "walnut": "snacks",
    "peanut": "snacks",
    "jerky": "snacks",
    "raisin": "snacks",
    "dried fruit": "snacks",
    "fruit snack": "snacks",
    "applesauce": "snacks",
    "rice cake": "snacks",
    "gum": "snacks",
    # ── beverages ────────────────────────────────────────────────────────────
    "soda": "beverages",
    "pop": "beverages",
    "cola": "beverages",
    "coke": "beverages",
    "pepsi": "beverages",
    "sprite": "beverages",
    "juice": "beverages",
    "orange juice": "beverages",
    "apple juice": "beverages",
    "water": "beverages",
    "sparkling water": "beverages",
    "coconut water": "beverages",
    "coffee": "beverages",
    "iced coffee": "beverages",
    "tea": "beverages",
    "lemonade": "beverages",
    "gatorade": "beverages",
    "sports drink": "beverages",
    "energy drink": "beverages",
    "kombucha": "beverages",
    "seltzer": "beverages",
    "ginger ale": "beverages",
    "cider": "beverages",
    "hot chocolate": "beverages",
    "smoothie": "beverages",
    "beer": "beverages",
    "wine": "beverages",
    # ── household ────────────────────────────────────────────────────────────
    "paper towel": "household",
    "toilet paper": "household",
    "napkin": "household",
    "tissue": "household",
    "trash bag": "household",
    "garbage bag": "household",
    "foil": "household",
    "aluminum foil": "household",
    "plastic wrap": "household",
    "sandwich bag": "household",
    "storage bag": "household",
    "ziploc": "household",
    "detergent": "household",
    "laundry detergent": "household",
    "dish soap": "household",
    "dishwasher": "household",
    "cleaner": "household",
    "bleach": "household",
    "disinfectant": "household",
    "sponge": "household",
    "paper plate": "household",
    "paper cup": "household",
    "plastic cup": "household",
    "candle": "household",
    "battery": "household",
    "light bulb": "household",
    "air freshener": "household",
    "fabric softener": "household",
    "dryer sheet": "household",
    "cleaning wipe": "household",
    # ── personal care / health ───────────────────────────────────────────────
    "shampoo": "personal",
    "conditioner": "personal",
    "soap": "personal",
    "body wash": "personal",
    "hand soap": "personal",
    "toothpaste": "personal",
    "toothbrush": "personal",
    "deodorant": "personal",
    "floss": "personal",
    "mouthwash": "personal",
    "razor": "personal",
    "shaving cream": "personal",
    "lotion": "personal",
    "sunscreen": "personal",
    "makeup": "personal",
    "cotton ball": "personal",
    "cotton swab": "personal",
    "bandage": "personal",
    "band aid": "personal",
    "aspirin": "personal",
    "ibuprofen": "personal",
    "tylenol": "personal",
    "advil": "personal",
    "vitamin": "personal",
    "medicine": "personal",
    "cold medicine": "personal",
    "allergy": "personal",
    "tampon": "personal",
    "maxi pad": "personal",
    "panty liner": "personal",
    "feminine": "personal",
    "lip balm": "personal",
    "chapstick": "personal",
    "hand sanitizer": "personal",
    "hairspray": "personal",
    # ── baby ─────────────────────────────────────────────────────────────────
    "diaper": "baby",
    "baby wipe": "baby",
    "formula": "baby",
    "baby food": "baby",
    "pacifier": "baby",
    "baby bottle": "baby",
    "milk collector": "baby",
    "breast milk": "baby",
    "breast pump": "baby",
    "breast pad": "baby",
    "nursing pad": "baby",
    "nursing": "baby",
    "teether": "baby",
    "sippy cup": "baby",
    "baby lotion": "baby",
    "baby shampoo": "baby",
    "baby wash": "baby",
    "diaper cream": "baby",
    "swaddle": "baby",
    "onesie": "baby",
    "crib": "baby",
    "stroller": "baby",
    "pull up": "baby",
    "huggies": "baby",
    "pampers": "baby",
    "enfamil": "baby",
    "similac": "baby",
}

# Longest first so a specific phrase wins over a generic word it contains ("milk collector" >
# "milk", "black pepper" > "pepper"). Precompiled word-boundary patterns with a tolerant trailing
# plural (`chip`→`chips`, `tomato`→`tomatoes`): a keyword matches only as a whole word/phrase, so
# "milk" can't fire on "buttermilk" and "chip" can't fire on "chipotle".
_ORDERED = sorted(_KEYWORDS.items(), key=lambda kv: len(kv[0]), reverse=True)
_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(rf"\b{re.escape(keyword)}(?:e?s)?\b"), category) for keyword, category in _ORDERED
]

# Product-form head words that name what an item *is* and must beat a longer word sitting in
# front of them: "pineapple juice" is a beverage, not produce, even though "pineapple" is the
# longer keyword the length-ordered table would pick. Checked *before* `_PATTERNS`, so the form
# word wins. Deliberately unambiguous only — "soda" is excluded because it collides with "baking
# soda" (pantry) and "soda bread" (bakery), which the length-ordered table already handles.
_PRIORITY: list[tuple[re.Pattern, str]] = [
    (re.compile(rf"\b{keyword}(?:e?s)?\b"), category)
    for keyword, category in (
        ("juice", "beverages"),
        ("lemonade", "beverages"),
        ("smoothie", "beverages"),
        ("kombucha", "beverages"),
    )
]


def guess_category(name: str) -> str | None:
    """Best-effort store category for a free-text item name; None when unsure.

    Matched against both the plain casefolded name and the merge-normalized form, so both the
    "cookies"→"cooky" quirk of `normalize_name` and its "berries"→"berry" fold are covered.
    """
    raw = " ".join(name.casefold().split())
    norm = normalize_name(name)
    for pattern, category in _PRIORITY:
        if pattern.search(raw) or pattern.search(norm):
            return category
    for pattern, category in _PATTERNS:
        if pattern.search(raw) or pattern.search(norm):
            return category
    return None
